# Generated by Django 5.2.5 on 2025-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Premise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.URLField(blank=True, null=True)),
                ('price', models.CharField(max_length=50)),
                ('available', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=list)),
                ('rating', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
